version: "2"
services:
  dbserver:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE

  microblog:
    depends_on:
      - dbserver
    image: microblog
    ports:
      - "80:5000"
    restart: always
    # healthcheck:
    #   test: ["CMD", "ping", "-c 3 localhost"]
    #   interval: 3s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 1s
    environment:
      SECRET_KEY: $MY_SECRET_KEY
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: true
      MAIL_USERNAME: $MY_GMAIL_USER
      MAIL_PASSWORD: $MY_GMAIL_PASSWORD
      DATABASE_URL: mysql+pymysql://$DB_USER:$DB_PASSWORD@dbserver/$DB_DATABASE
