version: "2"
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE

  microblog:
    depends_on:
      - db
    image: andriibondar/microblog
    volumes:
      - microbolog:/home/microblog
    ports:
      - "80:5000"
    restart: always
    healthcheck:
      test: ["CMD", "ping", "-c 3 localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
    environment:
      DB_SERVER: db
      DB_PASSWD: $DB_PASSWORD
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: epamdevopsd.ddns.net
      PS_ERASE_DB: 1

volumes:
  db_data: {}
  microblog: {}
