version: "2"
services:
  db:
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: microblog # $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: microblog #$DB_DATABASE

  microblog:
    depends_on:
      - db
    image: microblog
    ports:
      - "80:5000"
    restart: always
    links:
      - "db:dbserver"
    # healthcheck:
    #   test: ["CMD", "ping", "-c 3 localhost"]
    #   interval: 3s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 1s
    environment:
      SECRET_KEY: 87y7de6g636tgg # $MY_SECRET_KEY
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "true"
      MAIL_USERNAME: $MY_GMAIL_USER
      MAIL_PASSWORD: $MY_GMAIL_PASSWORD
      DATABASE_URL: mysql+pymysql://microblog:$DB_PASSWORD@db/microblog
      # DATABASE_URL: mysql+pymysql://$DB_USER:$DB_PASSWORD@db/$DB_DATABASE
